openapi: 3.0.2
info:
  title: ''
  version: ''
paths:
  /api/customers/:
    get:
      operationId: listCustomers
      description: ''
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Customer'
          description: ''
      tags:
      - api
    post:
      operationId: createCustomer
      description: ''
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Customer'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Customer'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Customer'
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Customer'
          description: ''
      tags:
      - api
  /api/customers/{id}/:
    get:
      operationId: retrieveCustomer
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this customer.
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Customer'
          description: ''
      tags:
      - api
    put:
      operationId: updateCustomer
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this customer.
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Customer'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Customer'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Customer'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Customer'
          description: ''
      tags:
      - api
    delete:
      operationId: destroyCustomer
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this customer.
        schema:
          type: string
      responses:
        '204':
          description: ''
      tags:
      - api
components:
  schemas:
    Customer:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        first_name:
          type: string
          maxLength: 50
        last_name:
          type: string
          maxLength: 50
      required:
      - first_name
      - last_name
