# Generated by Django 5.0 on 2023-12-15 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('CustomersID', models.IntegerField(primary_key=True, serialize=False)),
                ('FirstName', models.CharField(max_length=100)),
                ('LastName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('ProductID', models.IntegerField(primary_key=True, serialize=False)),
              cls  ('Name', models.CharField(max_length=100)),
                ('Price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('OrdersID', models.IntegerField(primary_key=True, serialize=False)),
                ('Quantity', models.IntegerField()),
                ('CreatedAt', models.DateField()),
                ('Customers_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.customers')),
                ('Product_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.products')),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('ReviewID', models.IntegerField(primary_key=True, serialize=False)),
                ('Rating', models.IntegerField()),
                ('Review', models.TextField()),
                ('Customers_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.customers')),
                ('Product_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.products')),
            ],
        ),
    ]
